# NOTE: Put "# <dev>" at the end of the line to specify that the package
#       is only needed for development and can be stripped out before running
#       CI for production images.

name: python-template
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  # Specify python version
  - python=3.12.3
  # pip
  - pip
  # Debugging
  - debugpy # <dev>
  # Formatting
  - yapf # <dev>
  # Jupyter notebook
  - nbformat # <dev>
  - nbstripout # <dev>
  - ipykernel # <dev>
  # Some common packages
  - pandas
  - numpy
  - plotly
  # pip packages - uncomment if needed (if a package is not available in other channels)
  # - pip:
  #     - opencv-contrib-python
